### ISSUE TITLE
checkout submit subissue

### ISSUE THREAD

**Issue by radical-ube** [wdf-2004-grace-shopper-team-e/grace-shopper-team-e#12]
- [ ] an express route to the backend post '/api/orders'
- [ ] should save all of the shipping info and payment info for this specific order
- [ ] if there is a user, relate this order to the user
- [ ] if there is a user, relate the shipping info and payment info to their profile
